handlers= java.util.logging.ConsoleHandler
.level= INFO

java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# Print only the log message followed by a newline
java.util.logging.SimpleFormatter.format = %5$s%n


